In [1]:
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.compose import make_column_transformer
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import OneHotEncoder

from sklearn.metrics import roc_auc_score, confusion_matrix

from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier


In [2]:
import  pandas as pd
import  numpy as np
import email_lead_scoring as els

# Leads Data
import  os
os.getcwd()

leads_df = els.read_and_process('x')


/Users/jp/miniconda3/envs/python_ds2_3.9/lib/python3.9/site-packages/janitor/utils.py:84: FutureWarning: PandasArray has been renamed NumpyExtensionArray. Use that instead. This alias will be removed in a future version.
  @_expand_grid.register(pd.arrays.PandasArray)


replacing tag_aws_webinar with 0
replacing tag_learning_lab with 0
replacing tag_learning_lab_05 with 0
replacing tag_learning_lab_09 with 0
replacing tag_learning_lab_11 with 0
replacing tag_learning_lab_12 with 0
replacing tag_learning_lab_13 with 0
replacing tag_learning_lab_14 with 0
replacing tag_learning_lab_15 with 0
replacing tag_learning_lab_16 with 0
replacing tag_learning_lab_17 with 0
replacing tag_learning_lab_18 with 0
replacing tag_learning_lab_19 with 0
replacing tag_learning_lab_20 with 0
replacing tag_learning_lab_21 with 0
replacing tag_learning_lab_22 with 0
replacing tag_learning_lab_23 with 0
replacing tag_learning_lab_24 with 0
replacing tag_learning_lab_25 with 0
replacing tag_learning_lab_26 with 0
replacing tag_learning_lab_27 with 0
replacing tag_learning_lab_28 with 0
replacing tag_learning_lab_29 with 0
replacing tag_learning_lab_30 with 0
replacing tag_learning_lab_31 with 0
replacing tag_learning_lab_32 with 0
replacing tag_learning_lab_33 with 0
replacin

In [3]:
leads_df

mailchimp_id          user_full_name                       user_email  \
0                 3       Garrick Langworth      garrick.langworth@gmail.com   
1                 4         Cordell Dickens        cordell.dickens@gmail.com   
2                 8               Inga Dach              inga.dach@gmail.com   
3                10     Ferdinand Bergstrom    ferdinand.bergstrom@gmail.com   
4                11          Justen Simonis         justen.simonis@gmail.com   
...             ...                     ...                              ...   
19914         33405   Ms. Felicity Moore MD   ms.felicity.moore.md@gmail.com   
19915         33406            Shirley Rowe           shirley.rowe@gmail.com   
19916         33407  Jarrett Walker-Carroll  jarrett.walkercarroll@gmail.com   
19917         33408            Tanja Herzog           tanja.herzog@gmail.com   
19918         33409          Farrell Murphy         farrell.murphy@gmail.com   

       member_rating optin_time country_code  time_as_subscriber email_sender  \
0                  2 2019-05-22           in                1769        gmail   
1                  4 2018-11-19        other                1953        gmail   
2                  2 2018-11-19        other                1953        gmail   
3                  2 2020-03-20           co                1466        gmail   
4                  2 2020-04-14        other                1441        gmail   
...              ...        ...          ...                 ...          ...   
19914              2 2018-11-18        other                1954        gmail   
19915              1 2019-03-12           br                1840        gmail   
19916              2 2019-09-09           in                1659        gmail   
19917              2 2019-10-24        other                1614        gmail   
19918              2 2020-06-19           ae                1375        gmail   

       tag_aws_webinar  tag_learning_lab  ...  tag_learning_lab_44  \
0                  0.0               1.0  ...                  0.0   
1                  0.0               0.0  ...                  0.0   
2                  0.0               0.0  ...                  0.0   
3                  0.0               1.0  ...                  0.0   
4                  0.0               0.0  ...                  0.0   
...                ...               ...  ...                  ...   
19914              0.0               0.0  ...                  0.0   
19915              0.0               0.0  ...                  0.0   
19916              0.0               0.0  ...                  0.0   
19917              0.0               1.0  ...                  0.0   
19918              0.0               0.0  ...                  0.0   

       tag_learning_lab_45  tag_learning_lab_46  tag_learning_lab_47  \
0                      0.0                  0.0                  0.0   
1                      0.0                  0.0                  0.0   
2                      0.0                  0.0                  0.0   
3                      0.0                  0.0                  0.0   
4                      0.0                  0.0                  0.0   
...                    ...                  ...                  ...   
19914                  0.0                  0.0                  0.0   
19915                  0.0                  0.0                  0.0   
19916                  0.0                  0.0                  0.0   
19917                  0.0                  0.0                  0.0   
19918                  0.0                  0.0                  0.0   

       tag_time_series_webinar  tag_webinar  tag_webinar_01  \
0                          0.0          1.0             0.0   
1                          0.0          0.0             0.0   
2                          0.0          0.0             0.0   
3                          0.0          0.0             0.0   
4                          0.0          0.0         

In [4]:
leads_df.columns

Index(['mailchimp_id', 'user_full_name', 'user_email', 'member_rating',
       'optin_time', 'country_code', 'time_as_subscriber', 'email_sender',
       'tag_aws_webinar', 'tag_learning_lab', 'tag_learning_lab_05',
       'tag_learning_lab_09', 'tag_learning_lab_11', 'tag_learning_lab_12',
       'tag_learning_lab_13', 'tag_learning_lab_14', 'tag_learning_lab_15',
       'tag_learning_lab_16', 'tag_learning_lab_17', 'tag_learning_lab_18',
       'tag_learning_lab_19', 'tag_learning_lab_20', 'tag_learning_lab_21',
       'tag_learning_lab_22', 'tag_learning_lab_23', 'tag_learning_lab_24',
       'tag_learning_lab_25', 'tag_learning_lab_26', 'tag_learning_lab_27',
       'tag_learning_lab_28', 'tag_learning_lab_29', 'tag_learning_lab_30',
       'tag_learning_lab_31', 'tag_learning_lab_32', 'tag_learning_lab_33',
       'tag_learning_lab_34', 'tag_learning_lab_35', 'tag_learning_lab_36',
       'tag_learning_lab_37', 'tag_learning_lab_38', 'tag_learning_lab_39',
       'tag_learning_lab

## standard model formula
y = b0 + b1X1 + e

In [5]:
# get rid of columns that dont have predictive power
x = leads_df.drop(['made_purchase', 'mailchimp_id', 'user_full_name',
                   'user_email', 'email_sender', 'optin_time'], axis = 1) 
x

member_rating country_code  time_as_subscriber  tag_aws_webinar  \
0                  2           in                1769              0.0   
1                  4        other                1953              0.0   
2                  2        other                1953              0.0   
3                  2           co                1466              0.0   
4                  2        other                1441              0.0   
...              ...          ...                 ...              ...   
19914              2        other                1954              0.0   
19915              1           br                1840              0.0   
19916              2           in                1659              0.0   
19917              2        other                1614              0.0   
19918              2           ae                1375              0.0   

       tag_learning_lab  tag_learning_lab_05  tag_learning_lab_09  \
0                   1.0                  0.0                  0.0   
1                   0.0                  0.0                  0.0   
2                   0.0                  0.0                  0.0   
3                   1.0                  0.0                  0.0   
4                   0.0                  0.0                  0.0   
...                 ...                  ...                  ...   
19914               0.0                  0.0                  0.0   
19915               0.0                  0.0                  0.0   
19916               0.0                  0.0                  0.0   
19917               1.0                  0.0                  0.0   
19918               0.0                  0.0                  0.0   

       tag_learning_lab_11  tag_learning_lab_12  tag_learning_lab_13  ...  \
0                      0.0                  1.0                  0.0  ...   
1                      0.0                  0.0                  0.0  ...   
2                      0.0                  0.0                  0.0  ...   
3                      0.0                  0.0                  0.0  ...   
4                      0.0                  0.0                  0.0  ...   
...                    ...                  ...                  ...  ...   
19914                  0.0                  0.0                  0.0  ...   
19915                  0.0                  0.0                  0.0  ...   
19916                  0.0                  0.0                  0.0  ...   
19917                  0.0                  0.0                  0.0  ...   
19918                  0.0                  0.0                  0.0  ...   

       tag_learning_lab_43  tag_learning_lab_44  tag_learning_lab_45  \
0                      0.0                  0.0                  0.0   
1                      0.0                  0.0                  0.0   
2                      0.0                  0.0                  0.0   
3                      0.0                  0.0                  0.0   
4                      0.0                  0.0                  0.0   
...                    ...                  ...                  ...   
19914                  0.0                  0.0                  0.0   
19915                  0.0                  0.0                  0.0   
19916                  0.0                  0.0                  0.0   
19917                  0.0                  0.0                  0.0   
19918                  0.0                  0.0                  0.0   

       tag_learning_lab_46  tag_learning_lab_47  tag_time_series_webinar  \
0                      0.0                  0.0                      0.0   
1                      0.0                  0.0                      0.0   
2                      0.0                  0.0                      0.0   
3                      0.0                  0.0                      0.0   
4                      0.0                  0.0                      0.0   
...                    ...                 

In [6]:
# explanatory / target variable
# target value is imbalanced 900/18000
y = leads_df['made_purchase']
y

0        1
1        1
2        1
3        1
4        0
        ..
19914    0
19915    0
19916    0
19917    0
19918    0
Name: made_purchase, Length: 19919, dtype: int64

## split the data

train and test, 80% and 20% respectively

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=345)

## Preprocessing

### nominal data to one hot encoding
one hot encoding is used to convert nominal data to numerical data
remaider = 'passthrough' is used to keep the other columns

In [8]:
enc = OneHotEncoder(handle_unknown='ignore')
transformer = make_column_transformer(
    (enc, ['country_code']),remainder='passthrough'
)
transformer

ColumnTransformer(remainder='passthrough',
                  transformers=[('onehotencoder',
                                 OneHotEncoder(handle_unknown='ignore'),
                                 ['country_code'])])

## pipeline
similar to tidymodels -> recipe, parsnip, workflow

In [9]:
pipeline_rf = make_pipeline(transformer, RandomForestClassifier())

## fit and predict model
use training set, proba gives the probability of the target variable

In [10]:
pipeline_rf.fit(x_train, y_train)
y_pred_prob = pipeline_rf.predict_proba(x_train)
y_pred_prob

array([[1.00000000e+00, 0.00000000e+00],
       [8.89435655e-01, 1.10564345e-01],
       [9.99891304e-01, 1.08695652e-04],
       ...,
       [1.00000000e+00, 0.00000000e+00],
       [8.75000000e-01, 1.25000000e-01],
       [1.00000000e+00, 0.00000000e+00]])

## metrics for the model
without parameter tuning

In [11]:
pipeline_rf.score(x_train, y_train)

0.9890178851584562

In [12]:

predicted_class_rf = pipeline_rf.predict_proba(x_train)[:,1] > 0.01 # select the second column

In [13]:
roc_auc_score(y_train, predicted_class_rf) # auc is area under the curve, 0.5 is random

0.8698924621872373

In [14]:
confusion_matrix(y_train, predicted_class_rf) # 3853 false positives, 2 false negatives

array([[11237,  3926],
       [    1,   771]])

## tune with grid search
grid search is used to find the best hyperparameters. Hyperparameter tuning is needed to have better performing model for new data and avoid overfitting. overfitting is when the model is too complex and performs too good on the training data but not on the test data.

In [26]:
grid_xgb=GridSearchCV(
    estimator = XGBClassifier(),
    param_grid = {
        'learning_rate': [0.01, 0.05,0.07,0.1, 0.3,0.5], # learning rate, how fast the model learns 
    },
    cv = 5,
    refit=True,
    scoring='roc_auc'
)

In [27]:
pipeline_xgb = make_pipeline(transformer, grid_xgb)
pipeline_xgb

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['country_code'])])),
                ('gridsearchcv',
                 GridSearchCV(cv=5,
                              estimator=XGBClassifier(base_score=None,
                                                      booster=None,
                                                      callbacks=None,
                                                      colsample_bylevel=None,
                                                      colsample_bynode=None,
                                                      colsample_bytree=None,
                                                      device=None...
                                                      learning_rate=None,
                                                      max_bin=None,
                                                      max_cat_threshold=None,
                                                      max_cat_to_onehot=None,
                                                      max_delta_step=None,
                                                      max_depth=None,
                                                      max_leaves=None,
                                                      min_child_weight=None,
                                                      missing=nan,
                                                      monotone_constraints=None,
                                                      multi_strategy=None,
                                                      n_estimators=None,
                                                      n_jobs=None,
                                                      num_parallel_tree=None,
                                                      random_state=None, ...),
                              param_grid={'learning_rate': [0.01, 0.05, 0.07,
                                                            0.1, 0.3, 0.5]},
                              scoring='roc_auc'))])

In [28]:
pipeline_xgb.fit(x_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['country_code'])])),
                ('gridsearchcv',
                 GridSearchCV(cv=5,
                              estimator=XGBClassifier(base_score=None,
                                                      booster=None,
                                                      callbacks=None,
                                                      colsample_bylevel=None,
                                                      colsample_bynode=None,
                                                      colsample_bytree=None,
                                                      device=None...
                                                      learning_rate=None,
                                                      max_bin=None,
                                                      max_cat_threshold=None,
                                                      max_cat_to_onehot=None,
                                                      max_delta_step=None,
                                                      max_depth=None,
                                                      max_leaves=None,
                                                      min_child_weight=None,
                                                      missing=nan,
                                                      monotone_constraints=None,
                                                      multi_strategy=None,
                                                      n_estimators=None,
                                                      n_jobs=None,
                                                      num_parallel_tree=None,
                                                      random_state=None, ...),
                              param_grid={'learning_rate': [0.01, 0.05, 0.07,
                                                            0.1, 0.3, 0.5]},
                              scoring='roc_auc'))])

In [29]:
pipeline_xgb.score(x_train, y_train)

0.8864075577344497

In [30]:
# best parameters
grid_xgb.best_params_

{'learning_rate': 0.1}

In [33]:
predict_proba_xgb = pipeline_xgb.predict_proba(x_train)[:,1] > 0.19
predict_proba_xgb

array([False, False, False, ..., False, False, False])

In [34]:
y_train

8020     0
9019     0
13896    0
7158     0
7830     0
        ..
1322     0
6980     0
16797    0
18639    0
3608     0
Name: made_purchase, Length: 15935, dtype: int64

xgboost with current parameters is worse than random forest model

In [32]:
roc_auc_score(y_train, predict_proba_xgb)

0.7395469234320385

In [ ]:
%%sql


In [35]:
confusion_matrix(y_train, predict_proba_xgb)

array([[14846,   317],
       [  386,   386]])

In [36]:
import joblib
joblib.dump(pipeline_rf, 'pipeline_rf.pkl')

['pipeline_rf.pkl']

In [ ]:
# load model
joblib.load('pipeline_rf.pkl')